apiVersion: v1
kind: Service
metadata:
  name: mynodejs-service
  namespace: default  # You can change this to your desired namespace
spec:
  type: NodePort  # Change to LoadBalancer if using a cloud provider
  ports:
    - port: 3000  # Change this to your application's port
      targetPort: 3000  # Container port
      nodePort: 30001  # Optional: specify a custom node port
  selector:
    app: mynodejs-application